content:
  value: '<p>Pro přihlášení vyberte svoji instituci a přihlaste se pomocí svých institucionálních přihlašovacích údajů. Pokud vaše instituce není přes e-INFRA přihlášení dostupná, můžete použít přihlášení přes ORCID nebo Google. Pokud se přihlašujete prvně, bude vaše registrace čekat na schválení.</p>'
  format: basic_html
