label: Soubory
display:
  default:
    display_title: Výchozí
    display_options:
      title: Soubory
      fields:
        filename:
          label: Název
          separator: ', '
        filemime:
          label: 'Typ MIME'
        filesize:
          label: Velikost
        status:
          label: Stav
          settings:
            format_custom_false: Dočasný
            format_custom_true: Trvalý
        changed:
          label: 'Datum změny'
        count:
          label: 'Použito v'
          format_plural_string: !!binary MSBwbGFjZQNAY291bnQgcGxhY2Vz
      pager:
        options:
          tags:
            next: 'Následující ›'
            previous: '‹ Předchozí'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      filters:
        filename:
          expose:
            label: 'Název souboru'
        filemime:
          expose:
            label: 'Typ MIME'
        status:
          expose:
            label: Stav
  page_1:
    display_options:
      menu:
        title: Soubory
  page_2:
    display_options:
      fields:
        entity_label:
          label: Entity
        type:
          label: 'Typ entity'
        count:
          format_plural_string: !!binary MQNAY291bnQ=
      pager:
        options:
          tags:
            next: 'Následující ›'
            previous: '‹ Předchozí'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      arguments:
        fid:
          exception:
            title: Vše
