display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      fields:
        title:
          label: Nadpis
          separator: ', '
      arguments:
        field_member_of_target_id:
          exception:
            title: Vše
  page_1:
    display_title: Stránka
