display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
          tags:
            previous: ‹‹
            next: ››
      fields:
        name:
          separator: ', '
      arguments:
        field_external_uri_uri:
          exception:
            title: Vše
  rest_export_1:
    display_options:
      arguments:
        name:
          exception:
            title: Vše
        vid:
          exception:
            title: Vše
