display:
  default:
    display_title: Nadřízené
    display_options:
      title: 'Moderovaný obsah'
      fields:
        nid:
          separator: ', '
        title:
          label: Nadpis
          separator: ', '
        type:
          label: 'Typ obsahu'
          separator: ', '
        name:
          label: Autor
          separator: ', '
        moderation_state:
          separator: ', '
        changed:
          label: Aktualizováno
          separator: ', '
        operations:
          label: Operace
      pager:
        options:
          tags:
            next: 'Následující ›'
            previous: '‹ Předchozí'
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      arguments:
        gid:
          exception:
            title: Vše
      filters:
        title:
          expose:
            label: Nadpis
        type:
          expose:
            label: 'Typ obsahu'
        langcode:
          expose:
            label: Jazyk
  moderated_content:
    display_title: 'Moderovaný obsah'
    display_options:
      menu:
        title: 'Moderovaný obsah'
