display:
  default:
    display_title: Nadřízené
    display_options:
      fields:
        node_bulk_form:
          action_title: Akce
        title:
          label: Nadpis
          separator: ', '
        operations:
          label: 'Odkazy na operace'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      arguments:
        field_member_of_target_id:
          exception:
            title: Vše
  page_1:
    display_title: Stránka
