display:
  default:
    display_options:
      fields:
        title:
          label: Nadpis
        status:
          label: Stav
      arguments:
        gid:
          exception:
            title: VÅ¡e
      filters:
        type:
          expose:
            label: Typ
