display:
  default:
    display_options:
      title: Média
      fields:
        media_bulk_form:
          action_title: Akce
      filters:
        name:
          expose:
            label: Název
  page:
    display_options:
      fields:
        media_bulk_form:
          action_title: Akce
        edit_media:
          text: Upravit
  widget:
    display_options:
      arguments:
        bundle:
          exception:
            title: Vše
      filters:
        name:
          expose:
            label: Název
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: Náhled
        name:
          label: Název
      arguments:
        bundle:
          exception:
            title: Vše
      filters:
        name:
          expose:
            label: Název
