display:
  default:
    display_options:
      fields:
        title:
          label: Nadpis
        status:
          label: Stav
      exposed_form:
        options:
          submit_button: Filtr
      filters:
        title:
          expose:
            label: Nadpis
        status:
          expose:
            label: Stav
