display:
  default:
    display_options:
      fields:
        type:
          label: Typ
        message:
          label: Zpr√°va
      exposed_form:
        options:
          submit_button: Filtr
      filters:
        type:
          expose:
            label: Typ
