display:
  default:
    display_title: Výchozí
    display_options:
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      filters:
        access:
          expose:
            label: 'Poslední přístup'
