display:
  default:
    display_options:
      fields:
        title:
          label: Nadpis
      exposed_form:
        options:
          submit_button: Filtr
      arguments:
        gid:
          exception:
            title: VÅ¡e
      filters:
        title:
          expose:
            label: Nadpis
