display:
  default:
    display_options:
      pager:
        options:
          tags:
            first: '« První'
            last: 'Poslední »'
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      header:
        result:
          content: '@start - @end z @total souborů v datasetu'
      exposed_form:
        options:
          submit_button: Použít
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      fields:
        name:
          label: Název
          separator: ', '
        bundle:
          separator: ', '
        field_mime_type:
          label: 'Typ MIME'
          separator: ', '
        changed:
          label: Změněno
          separator: ', '
      arguments:
        field_media_of_target_id:
          exception:
            title: Vše
    display_title: Nadřízené
  entity_view_1:
    display_options:
      title: 'Přehled datasetu'
      fields:
        name:
          label: Název
        field_file_size_value:
          label: 'Velikost souboru'
        field_is_derived_from:
          label: 'Je odvozeno z'
  page_1:
    display_title: Stránka
    display_options:
      menu:
        title: Média
      fields:
        media_bulk_form:
          action_title: Akce
        name:
          label: Název
          separator: ', '
        bundle:
          separator: ', '
        field_mime_type:
          label: 'Typ MIME'
          separator: ', '
        field_media_use:
          separator: ', '
        changed:
          label: Změněno
          separator: ', '
  rest_export_1:
    display_options:
      fields:
        name:
          label: Název
          separator: ', '
        bundle:
          separator: ', '
        field_mime_type:
          label: 'Typ MIME'
          separator: ', '
        changed:
          label: Změněno
          separator: ', '
