display:
  default:
    display_options:
      fields:
        timestamp:
          label: Čas
        message:
          label: Zpráva
      filters:
        timestamp_1:
          expose:
            label: Komu
