_core:
  default_config_hash: zDwqaWPY76K_8TgX6aS789W7nZIEg7lU9MJsoh61bAU
minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 100
max_shown_results: null
use_relative_width: true
jquery_selector: 'select:visible, select.form-select'
search_contains: false
disable_search: false
allow_single_deselect: false
allow_mobile: false
add_helper_buttons: false
disabled_themes:
  olivero: '0'
  claro: '0'
  bartik: '0'
  islandora_muni: '0'
  gin: '0'
chosen_include: 2
placeholder_text_multiple: '- All -'
placeholder_text_single: '- All -'
no_results_text: 'No results match'
