_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  auto_entitylabel: -100
  action: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  basic_auth: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bpmn_io: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_lib: 0
  citation_select: 0
  ckeditor5: 0
  coi: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_override_core_fields: 0
  config_translation: 0
  config_update: 0
  contact: 0
  content_moderation: 0
  context: 0
  context_ui: 0
  contextual: 0
  controlled_access_terms: 0
  controlled_access_terms_defaults: 0
  csv_serialization: 0
  csvfile_formatter: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dgi_image_discovery: 0
  digitalia_muni_entity: 0
  digitalia_muni_workbench_ingest: 0
  doi_datacite: 0
  download_file: 0
  dynamic_page_cache: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_config: 0
  eca_content: 0
  eca_endpoint: 0
  eca_file: 0
  eca_menu: 0
  eca_migrate: 0
  eca_misc: 0
  eca_modeller_bpmn: 0
  eca_queue: 0
  eca_render: 0
  eca_ui: 0
  eca_user: 0
  eca_views: 0
  eca_workflow: 0
  editor: 0
  entity: 0
  epp: 0
  eva: 0
  facets: 0
  facets_exposed_filters: 0
  facets_rest: 0
  facets_searchbox_widget: 0
  facets_summary: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_report: 0
  field_ui: 0
  field_validation: 0
  file: 0
  file_delete: 0
  file_replace: 0
  filehash: 0
  filter: 0
  flexible_permissions: 0
  flysystem: 0
  fpa: 0
  gcontent_moderation: 0
  geofield: 0
  geolocation: 0
  geolocation_geometry: 0
  geolocation_leaflet: 0
  gin_toolbar: 0
  gnode: 0
  grequest: 0
  group: 0
  group_action: 0
  hal: 0
  hdl: 0
  help: 0
  history: 0
  ief_table_view_mode: 0
  image: 0
  inline_entity_form: 0
  islandora: 0
  islandora_audio: 0
  islandora_breadcrumbs: 0
  islandora_core_feature: 0
  islandora_fits: 0
  islandora_iiif: 0
  islandora_image: 0
  islandora_mirador: 0
  islandora_text_extraction: 0
  islandora_text_extraction_defaults: 0
  islandora_video: 0
  islandora_workbench_integration: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  js_cookie: 0
  jsonld: 0
  jwt: 0
  key: 0
  language: 0
  leaflet: 0
  link: 0
  locale: 0
  masquerade: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  openid_connect: 0
  openseadragon: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pdf: 0
  persistent_identifiers: 0
  pgsql: 0
  phpass: 0
  prepopulate: 0
  rdf: 0
  recaptcha: 0
  responsive_image: 0
  rest: 0
  rest_oai_pmh: 0
  restui: 0
  search_api: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  sqlite: 0
  state_machine: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  taxonomy_manager_merge: 0
  term_merge: 0
  term_reference_change: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tracer: 0
  twig_tweak: 0
  update: 0
  user: 0
  view_unpublished: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_field_view: 0
  views_nested_details: 0
  views_ui: 0
  workflows: 0
  pathauto: 1
  content_translation: 10
  externalauth: 10
  views: 10
  minimal: 1000
theme:
  olivero: 0
  claro: 0
  bartik: 0
  islandora_muni: 0
  gin: 0
profile: minimal
