_core:
  default_config_hash: Yo9I-9cCMhnGRddog63IHfaD1MW-X7LIiPZnK8KLvEU
doi_datacite_api_endpoint: 'https://api.test.datacite.org/dois'
doi_datacite_prefix: '10.80626'
doi_datacite_suffix_source: uuid
doi_datacite_username: UPWJ.PYRXWM
doi_datacite_password: ''
doi_datacite_creators_mapping: ''
doi_datacite_publisher_mapping: ''
doi_datacite_publicationyear_mapping: field_edtf_date_issued
doi_datacite_creators_mapping_dataset: ''
doi_datacite_publisher_mapping_dataset: ''
doi_datacite_publicationyear_mapping_dataset: field_date_issued
