_core:
  default_config_hash: c8aZhkIY8zHUo0_UOll4vVs_l48dHL_gBqbvfuAM0Rs
favicon:
  mimetype: image/svg+xml
  path: themes/custom/islandora_muni/platform_specific/images/favicon.svg
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: themes/custom/islandora_muni/platform_specific/images/ArchaeoVault.png
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: dark_purple
preset_focus_color: gin
enable_darkmode: '0'
classic_toolbar: horizontal
secondary_toolbar_frontend: true
high_contrast_mode: false
accent_color: ''
focus_color: ''
layout_density: small
show_description_toggle: true
show_user_theme_settings: false
sticky_action_buttons: true
