_core:
  default_config_hash: u1W0SzrexeSsiBpFn60VZX6MHJ-BOj_P_uSCSWmcxc4
persistent_identifiers_target_field: field_doi
persistent_identifiers_persister: persistent_identifiers.persister.generic
persistent_identifiers_minter: doi_datacite.minter.datacitedois
persistent_identifiers_bundles:
  - dataset
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
persistent_identifiers_map_to_schema_sameas: 0
persistent_identifiers_resolver_base_url: ''
